# Generated by Django 4.2.1 on 2023-05-09 21:41

import car_collection_app.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_car_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(validators=[car_collection_app.web.models.validation_car_year]),
        ),
    ]
