# Generated by Django 4.1.6 on 2023-02-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web', '0003_alter_profile_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ('id', 'name')},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='album',
            name='image_url',
            field=models.URLField(verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(
                max_length=30,
                unique=True,
                verbose_name='Album Name'
            ),
        ),
    ]
