# Generated by Django 4.2.1 on 2023-06-01 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_photo_user'),
        ('common', '0004_like_user_alter_comment_text_alter_comment_to_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='to_photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='photos.photo'),
        ),
    ]
