# Generated by Django 4.2.1 on 2023-05-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('id',)},
        ),
    ]
